In [ ]:
import pandas as pd


In [ ]:
df = pd.read_csv('/content/train_anxiety.csv')

In [ ]:
df.head

<bound method NDFrame.head of        EMPLOYEE ID  AGE  GENDER  Q1  Q2  Q3  Q4  Q5  Q6  Q7  STRESS VALUE  \
0        #fffffff1   26    Male   3   1   3   0   1   0   3             2   
1        #fffffff2   29  Female   3   3   3   2   2   2   2             3   
2        #fffffff3   30  Female   0   2   1   1   2   3   2             2   
3        #fffffff4   31    Male   0   1   3   0   3   0   1             1   
4        #fffffff5   34  Female   3   1   2   2   3   2   0             2   
...            ...  ...     ...  ..  ..  ..  ..  ..  ..  ..           ...   
2506  #fffffff2507   57  Female   2   1   1   2   0   2   1             1   
2507  #fffffff2508   28  Female   2   2   3   0   0   0   0             1   
2508  #fffffff2509   52    Male   1   0   2   3   0   3   0             1   
2509  #fffffff2510   31    Male   0   2   0   3   1   1   2             1   
2510  #fffffff2511   33  Female   0   1   0   3   2   2   0             1   

      GAD SCORE  
0            11  
1        

In [ ]:
df.drop(["EMPLOYEE ID","GENDER"],axis=1, inplace=True)

In [ ]:
df.head

<bound method NDFrame.head of       AGE  Q1  Q2  Q3  Q4  Q5  Q6  Q7  STRESS VALUE  GAD SCORE
0      26   3   1   3   0   1   0   3             2         11
1      29   3   3   3   2   2   2   2             3         17
2      30   0   2   1   1   2   3   2             2         11
3      31   0   1   3   0   3   0   1             1          8
4      34   3   1   2   2   3   2   0             2         13
...   ...  ..  ..  ..  ..  ..  ..  ..           ...        ...
2506   57   2   1   1   2   0   2   1             1          9
2507   28   2   2   3   0   0   0   0             1          7
2508   52   1   0   2   3   0   3   0             1          9
2509   31   0   2   0   3   1   1   2             1          9
2510   33   0   1   0   3   2   2   0             1          8

[2511 rows x 10 columns]>

In [ ]:
dataset = df.values

In [ ]:
X = dataset[:,1:8]
Y = dataset[:,8]

In [ ]:
Y

array([2, 3, 2, ..., 1, 1, 1])

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train , X_test , Y_train , Y_test = train_test_split(X,Y,test_size = 0.3)

In [ ]:
from keras.models import Sequential
from keras.layers import Dense

In [ ]:
model = Sequential([Dense(32,activation = 'relu',input_shape=(7,)),
                    Dense(32, activation = 'relu'),
                    Dense(4,activation = 'softmax')
                    ])

In [ ]:
import tensorflow as tf

In [ ]:
import numpy as np


In [51]:
mgd = tf.keras.optimizers.SGD(learning_rate=0.01, momentum=0.9)

In [52]:
model.compile(optimizer=mgd,loss='sparse_categorical_crossentropy',metrics=['accuracy'])

In [53]:
hist = model.fit(X_train,Y_train,batch_size=32,epochs=100)

Epoch 1/100
55/55 [==============================] - 1s 2ms/step - loss: 0.0032 - accuracy: 1.0000
Epoch 2/100
55/55 [==============================] - 0s 2ms/step - loss: 0.0034 - accuracy: 1.0000
Epoch 3/100
55/55 [==============================] - 0s 2ms/step - loss: 0.0029 - accuracy: 1.0000
Epoch 4/100
55/55 [==============================] - 0s 2ms/step - loss: 0.0027 - accuracy: 1.0000
Epoch 5/100
55/55 [==============================] - 0s 2ms/step - loss: 0.0029 - accuracy: 1.0000
Epoch 6/100
55/55 [==============================] - 0s 2ms/step - loss: 0.0028 - accuracy: 1.0000
Epoch 7/100
55/55 [==============================] - 0s 2ms/step - loss: 0.0026 - accuracy: 1.0000
Epoch 8/100
55/55 [==============================] - 0s 2ms/step - loss: 0.0025 - accuracy: 1.0000
Epoch 9/100
55/55 [==============================] - 0s 2ms/step - loss: 0.0024 - accuracy: 1.0000
Epoch 10/100
55/55 [==============================] - 0s 2ms/step - loss: 0.0025 - accuracy: 1.0000
Epoch 11/

In [54]:
model.evaluate(X_test,Y_test)[1]

24/24 [==============================] - 0s 2ms/step - loss: 9.6133e-04 - accuracy: 1.0000


1.0

In [ ]:
X_test[3:4]

array([[3, 2, 0, 0, 2, 2, 1]])

In [ ]:
tt = np.array([[2,1,3,1,0,1,3]])

In [ ]:
pred = model.predict(tt)

1/1 [==============================] - 0s 25ms/step


In [ ]:
pred.shape

(1, 4)

In [ ]:
pred

array([[1.1657359e-19, 9.0670566e-10, 1.0000000e+00, 2.9634674e-13]],
      dtype=float32)

In [61]:
import pickle
pickle.dump(model,open('anx_model.pkl','wb'))

In [62]:
a_model = pickle.load(open('anx_model.pkl','rb'))

In [63]:
a_model.predict(tt)

1/1 [==============================] - 0s 72ms/step


array([[4.0255316e-25, 7.9386039e-11, 1.0000000e+00, 4.1833514e-18]],
      dtype=float32)