In [1]:
import pandas as pd
import tensorflow as tf
import numpy as np

In [2]:
df = pd.read_csv('/content/train_depression.csv')

In [3]:
df.head

<bound method NDFrame.head of        EMPLOYEE ID  AGE  GENDER  Q1  Q2  Q3  Q4  Q5  Q6  Q7  Q8  Q9  \
0        #fffffff1   27    Male   3   0   1   0   2   3   2   0   1   
1        #fffffff2   36    Male   3   1   1   3   3   0   1   1   2   
2        #fffffff3   25    Male   2   1   2   1   3   2   0   0   3   
3        #fffffff4   30    Male   0   3   0   3   0   2   0   1   2   
4        #fffffff5   61    Male   2   0   1   3   2   1   0   1   0   
...            ...  ...     ...  ..  ..  ..  ..  ..  ..  ..  ..  ..   
2495  #fffffff2496   64  Female   2   3   2   0   2   1   3   1   0   
2496  #fffffff2497   30    Male   1   2   2   1   1   1   2   3   1   
2497  #fffffff2498   28    Male   0   0   3   2   3   1   0   3   0   
2498  #fffffff2499   40    Male   0   0   1   0   1   2   3   0   1   
2499  #fffffff2500   46    Male   1   1   2   2   1   1   0   2   1   

      STRESS VALUE  PHQ SCORE  
0                2         12  
1                3         15  
2                2   

In [4]:
df.drop(['EMPLOYEE ID','GENDER'],axis=1,inplace = True) 

In [5]:
df.head

<bound method NDFrame.head of       AGE  Q1  Q2  Q3  Q4  Q5  Q6  Q7  Q8  Q9  STRESS VALUE  PHQ SCORE
0      27   3   0   1   0   2   3   2   0   1             2         12
1      36   3   1   1   3   3   0   1   1   2             3         15
2      25   2   1   2   1   3   2   0   0   3             2         14
3      30   0   3   0   3   0   2   0   1   2             2         11
4      61   2   0   1   3   2   1   0   1   0             2         10
...   ...  ..  ..  ..  ..  ..  ..  ..  ..  ..           ...        ...
2495   64   2   3   2   0   2   1   3   1   0             2         14
2496   30   1   2   2   1   1   1   2   3   1             2         14
2497   28   0   0   3   2   3   1   0   3   0             2         12
2498   40   0   0   1   0   1   2   3   0   1             1          8
2499   46   1   1   2   2   1   1   0   2   1             2         11

[2500 rows x 12 columns]>

In [6]:
dataset = df.values

In [7]:
X  = dataset[:,1:10]
Y = dataset[:,10]

In [8]:
X

array([[3, 0, 1, ..., 2, 0, 1],
       [3, 1, 1, ..., 1, 1, 2],
       [2, 1, 2, ..., 0, 0, 3],
       ...,
       [0, 0, 3, ..., 0, 3, 0],
       [0, 0, 1, ..., 3, 0, 1],
       [1, 1, 2, ..., 0, 2, 1]])

In [9]:
Y

array([2, 3, 2, ..., 2, 1, 2])

In [10]:
from sklearn.model_selection import train_test_split
X_train ,X_test, Y_train, Y_test = train_test_split(X,Y,test_size = 0.3)

In [15]:
from keras.models import Sequential
from keras.layers import Dense

In [16]:
dep_model = Sequential([ Dense(32,activation='relu',input_shape = (9,)),
                        Dense(32,activation = 'relu'),
                        Dense(5, activation = 'softmax')])

In [17]:
mgd = tf.keras.optimizers.SGD(learning_rate=0.01, momentum=0.9)

In [18]:
dep_model.compile(optimizer=mgd,loss='sparse_categorical_crossentropy',metrics=['accuracy'])

In [19]:
hist = dep_model.fit(X_train,Y_train,batch_size=32,epochs=100)

Epoch 1/100
55/55 [==============================] - 1s 2ms/step - loss: 1.1409 - accuracy: 0.4909
Epoch 2/100
55/55 [==============================] - 0s 2ms/step - loss: 0.9699 - accuracy: 0.6166
Epoch 3/100
55/55 [==============================] - 0s 2ms/step - loss: 0.8738 - accuracy: 0.6480
Epoch 4/100
55/55 [==============================] - 0s 2ms/step - loss: 0.7357 - accuracy: 0.7149
Epoch 5/100
55/55 [==============================] - 0s 2ms/step - loss: 0.6064 - accuracy: 0.7606
Epoch 6/100
55/55 [==============================] - 0s 2ms/step - loss: 0.5187 - accuracy: 0.7983
Epoch 7/100
55/55 [==============================] - 0s 2ms/step - loss: 0.4354 - accuracy: 0.8480
Epoch 8/100
55/55 [==============================] - 0s 2ms/step - loss: 0.3913 - accuracy: 0.8640
Epoch 9/100
55/55 [==============================] - 0s 2ms/step - loss: 0.3635 - accuracy: 0.8611
Epoch 10/100
55/55 [==============================] - 0s 2ms/step - loss: 0.3341 - accuracy: 0.8697
Epoch 11/

In [21]:
dep_model.evaluate(X_test,Y_test)[1]

24/24 [==============================] - 0s 2ms/step - loss: 0.0340 - accuracy: 0.9920


0.9919999837875366

In [24]:
tt = np.array([[2,1,2,1,0,1,1,0,1]])

In [26]:
pred = dep_model.predict(tt)

1/1 [==============================] - 0s 36ms/step


In [ ]:
np.argmax(pred)

In [28]:
import pickle

In [30]:
pickle.dump(dep_model,(open('dep_model.pkl','wb')))

In [31]:
d_model = pickle.load(open('dep_model.pkl','rb'))
d_model.predict(tt)

1/1 [==============================] - 0s 97ms/step


array([[4.8577560e-05, 9.9097472e-01, 8.9766905e-03, 9.3029509e-17,
        9.5799217e-34]], dtype=float32)